# -*- Makefile -*-
test: 0_testfile0.cpp
	g++ -std=c++17 0_testfile0.cpp -lm
	a

Q1: 1_question1.cpp
	g++ -std=c++17 1_question1.cpp -lm
	a

Q2: 2_question2.cpp
	g++ -std=c++17 2_question2.cpp -lm
	a

Q3: 3_question3.cpp
	g++ -std=c++17 3_question3.cpp -lm
	a

Q4: 4_question4.cpp
	g++ -std=c++17 4_question4.cpp -lm
	a
