# -*- Makefile -*-

Q1: 1_question1.cpp
	g++ -std=c++17 1_question1.cpp -lm
	./a.out

Q2: 2_question2.cpp
	g++ -std=c++17 2_question2.cpp -lm
	./a.out

Q3: 3_question3.cpp
	g++ -std=c++17 3_question3_v2.cpp -lm
	./a.out
	
Q4: 4_question4.cpp
	g++ -std=c++17 4_question4.cpp -lm
	./a.out
